### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by hwfan** [caiyuanhao1998/HDR-GS#1]
Thanks for your excellent work! When will the code be released?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest. Our paper is still in submission. Code will be released after our paper is accepted. Stay tuned. Thanks for your patience.

By the way, we just released our CVPR 2024 work "Structure-Aware Sparse-View X-ray 3D Reconstruction" in [this repo](https://github.com/caiyuanhao1998/SAX-NeRF). This work also studies NeRF and 3D Vision. Feel free to use them :)

**Comment by GopiRajuMatta** [comment]
Waiting for the code release? Any tentative timeline for the same?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest. Our paper is still in submission. Code will be released after our paper is accepted. I will let you know then. Stay tuned. Thanks for your patience.

**Comment by TejasCThakare** [comment]
Can you please release the code, it will be of great help..

**Comment by yiyulics** [comment]
Hi Yuanhao, congrats on the NeurIPS acceptance!!! Could you please release the code? It would be very helpful.

**Comment by caiyuanhao1998** [comment]
> Hi Yuanhao, congrats on the NeurIPS acceptance!!! Could you please release the code? It would be very helpful.

Hi, thank you. Code will be released before the start date of NeurIPS 2024 (2024.12.10). Stay tuned!

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interets

Code and data have been released. Feel free to check!

If you find our repo useful, please help us star it. Thanks
