### ISSUE TITLE
submodules, missing .gitmodules?

### ISSUE THREAD

**Issue by briandoman** [caiyuanhao1998/HDR-GS#3]
Hello,

Thanks for publishing the code.  I notice that the env yml calls for submodules, should we be seeing a .gitmodules file in the repo?

Regards,

 - BD

**Comment by briandoman** [comment]
Thanks I see the update -- closing!

**Comment by teacupboy** [comment]
I will continue constructing this repo and fixing problems. Just let me
know. btw, could you please help us star our repo?
