### ISSUE TITLE
How to train our own scene

### ISSUE THREAD

**Issue by XLR-man** [caiyuanhao1998/HDR-GS#5]
As title, How can we train our own scenes, what are requirements about it to train,

**Comment by XLR-man** [comment]
![image](https://github.com/user-attachments/assets/2d4f448a-c5ec-44b9-9120-540f276da682)
In real scene, you don't need to get points from sparse/0/ , just initilize point clouds randomly?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest

(i) You need to run SfM algorithms to calibrate the multi-view images of the scene like we do in the paper.

(ii) We also need `sparse/0/`. We provide this data in the google drive.

If you find our repo useful, please help us star it, thanks :)

**Comment by XLR-man** [comment]
Thanks for your reply.
(i) I am confused that if i have a real scene with not only 5 exposures but more than 5, is that mean i need to pick one exposure and use these images to run sfm? 
(ii) i see there is `sparse/0/` in your scenes, but from your code, it seems you don't use it under real scenes but use `poses_bound_exp.npy` to get poses and other info. and initilize point clouds randomly. So we need to get poses from sfm first, and don't use point clouds in `sparse/0/` but initilize randomly?
