### ISSUE TITLE
how do i create poses_bounds_exps.npy from my own dataset?

### ISSUE THREAD

**Issue by zhj296409022** [caiyuanhao1998/HDR-GS#6]

**Comment by caiyuanhao1998** [comment]
Hi, for real scenes. We do not need poses and bounds in the file `poses_bounds_exps.npy`

We just use the exp time in `poses_bounds_exps.npy`. The camera poses are read from the `sparse/0/`

So I suggest you read the exposure time from the camera output raw file. And then use COLMAP to compute the camera poses.
