### ISSUE TITLE
Problems when reproducing your excellent work

### ISSUE THREAD

**Issue by Honey-ashead** [caiyuanhao1998/HDR-GS#7]
First of all, I was very excited after reading your paper and thanks for your contributions. However, when I tried to reproduce your work with the codes and instructions you provided, I met the following problems:
1. I noticed that when training the project, the command you provided has a parameter called `--eval`, I think it is quite strange to use the parameter when training a neural network based project.
2. You didn't provide the specific version of some critical packages, e.g. imageio, etc, which could be better if you can provide more details.
3. Since you were using Python 3.7.13 when carrying on this work, all the corresponding packages are based on Python 3.7, which is not supported by some IDE such as VS Code.
4. When I read your code, I notice that there is a line, `video_inference(0, scene, render, (pipe, background))`. I wonder why you use the results of the 0th iteration to evaluate the performance of the model.

I am looking forward for your reply!

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

1. eval means doing the evaluation

2. imageio is used to save images. You can install it with pip

3. They are supported. I have tried many times.

4. That just make sure it can work. You can change it if it matters.

If you find our repo useful, please help us star it, thanks :)
